var data = {
  status: "Success",
  internships: [
    {
      internship_quality: "Hot",
      title: "Business Development Intern",
      company_name: "Finbricks",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "real estate",
      stipend_type: "Variable",
      stipend: "10000 - 12000 per month",
      days_left: 7,
      slug: "real-estate-internship-at-finbricks-2qjtn",
      logo: "uploads/company/logos/3cdd6cced1a455d7623c5319436acdcf3408009b.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Business Development",
      company_name: "Ministry of New",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "sales",
      stipend_type: "Incentive Based",
      stipend: "5000 per sale",
      days_left: 27,
      slug: "sales-internship-at-ministry-of-new-shpp6",
      logo: "uploads/company/logos/f28e09eca7c1e218295c46085027e09e3f26d54d.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Video Editor",
      company_name: "Swamonk Educare",
      location: "faridabad",
      internship_type: "Part Time",
      category_name: "video editor",
      stipend_type: "Fixed",
      stipend: "3500 per month",
      days_left: 26,
      slug: "video-editor-internship-at-swamonk-educare-idmx0",
      logo: "uploads/company/logos/22b08b0fbbc16e07e4ec40860d725bdcfd37a735.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Marketing Internship",
      company_name: "Think and Learn Pvt Ltd",
      location: "ahmedabad",
      internship_type: "Full Time",
      category_name: "marketing",
      stipend_type: "Fixed",
      stipend: "18000 per month",
      days_left: 25,
      slug: "marketing-internship-at-think-and-learn-pvt-ltd-mfbdt",
      logo: "uploads/company/logos/bdc2fb3214ab03616ab475fe2f360cb8b837aa87.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Marketing Ambassador  - Work from Home",
      company_name: "Laugh Out Loud Ventures",
      location: "bangalore,chennai,delhi,mumbai,pune,thane",
      internship_type: "Work From Home",
      category_name: "marketing",
      stipend_type: "Variable",
      stipend: "3000 - 10000 per month",
      days_left: 25,
      slug: "marketing-internship-at-laugh-out-loud-ventures-hkenx",
      logo: "uploads/company/companylogos/62362fbf882221470f099d8d0a119df93ce19831/7e34b7356b30b3696d14fcab94c6e8989a42fd69com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Search Engine Optimisation",
      company_name: "Sizzling Career Solutions Pvt Ltd.",
      location: "delhi",
      internship_type: "Full Time",
      category_name: "SEO",
      stipend_type: "Variable",
      stipend: "5000 - 10000 per month",
      days_left: 24,
      slug: "seo-internship-at-sizzling-career-solutions-pvt-ltd-39tzp",
      logo: "uploads/company/companylogos/5b17adc969018b102b802193f65ffebc07494a2c/7c483889017d4bef536927bf5820941e35f05657com.jpeg",
    },
    {
      internship_quality: "Normal",
      title: " Talent Acquisition, HR Recruiter",
      company_name: "Nimbus Logistics",
      location: "thane",
      internship_type: "Full Time",
      category_name: "human resources",
      stipend_type: "Variable",
      stipend: "3000 - 5000 per month",
      days_left: 23,
      slug: "human-resources-internship-at-nimbus-logistics-s2uog",
      logo: "uploads/company/companylogos/e659b3b149dd5355940bc7ff40dbee2f0f53b22a/2cdd8e5a8b7f7a140f8711f385755340c64b76d5com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Business strategy",
      company_name: "Magic factory",
      location: "hyderabad,bangalore,mumbai,delhi,kolkata",
      internship_type: "Work From Home,Full Time",
      category_name: "general management",
      stipend_type: "Variable",
      stipend: "7000 - 10000 per month",
      days_left: 23,
      slug: "general-management-internship-at-magic-factory-1pg0v",
      logo: "uploads/company/logos/cb107f6e62308e242a975eb4664f180929f67dad.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Intern",
      company_name: "ABC Consultants",
      location: "delhi",
      internship_type: "Full Time",
      category_name: "human resources",
      stipend_type: "Fixed",
      stipend: "6000 per month",
      days_left: 22,
      slug: "human-resources-internship-at-abc-consultants-0xb0l",
      logo: "uploads/company/companylogos/768136d410e350e1646ec0f32e49544d7fb4ce73/d937822d046b705e8aa58936809171cd709d2cb3com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Content Writer",
      company_name: "Instaastro Technology Pvt. Ltd.",
      location: "noida",
      internship_type: "Full Time",
      category_name: "content writing",
      stipend_type: "Fixed",
      stipend: "5000 per month",
      days_left: 22,
      slug: "content-writing-internship-at-instaastro-technology-pvt-ltd-gvdbl",
      logo: "uploads/company/logos/40d8069a92d3926dbf328356fe32d4d9f12f870e.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Business Development",
      company_name: "Oddy Labs",
      location: "hyderabad,delhi",
      internship_type: "Full Time,Work From Home",
      category_name: "business development",
      stipend_type: "Fixed",
      stipend: "4000 per month",
      days_left: 21,
      slug: "business-development-internship-at-oddy-labs-nngle",
      logo: "uploads/company/logos/76a0ec84f95f4b7a450d53b5953bdf17802f62ce.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Blog writer intern",
      company_name: "Oddy Labs",
      location: "hyderabad,delhi",
      internship_type: "Full Time,Work From Home",
      category_name: "content writing",
      stipend_type: "Fixed",
      stipend: "4000 per month",
      days_left: 21,
      slug: "content-writing-internship-at-oddy-labs-52q1s",
      logo: "uploads/company/logos/76a0ec84f95f4b7a450d53b5953bdf17802f62ce.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Search Engine Optimization (SEO)",
      company_name: "Re-Engineering Business Solutions Pvt Ltd.",
      location: "pune",
      internship_type: "Full Time",
      category_name: "SEO",
      stipend_type: "Fixed",
      stipend: "5000 per month",
      days_left: 21,
      slug: "seo-internship-at-re-engineering-business-solutions-pvt-ltd-3dd84",
      logo: "uploads/company/logos/e75a764228e8ecaf9b416e1084ef891eddca8b25.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Video Editor",
      company_name: "The Marketeers Hub",
      location: "delhi,bangalore,chandigarh,pune,ahmedabad,hyderabad",
      internship_type: "Full Time,Work From Home",
      category_name: "video editor",
      stipend_type: "Fixed",
      stipend: "3000 per month",
      days_left: 19,
      slug: "video-editor-internship-at-the-marketeers-hub-yt9na",
      logo: "uploads/company/logos/685212f735f8bfe83494c50f05d9068555ee6e2d.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Social media marketer",
      company_name: "The Marketeers Hub",
      location: "delhi,chandigarh,bangalore,pune,hyderabad,sonipat,meerut",
      internship_type: "Full Time,Work From Home",
      category_name: "social media",
      stipend_type: "Fixed",
      stipend: "3000 per month",
      days_left: 19,
      slug: "social-media-internship-at-the-marketeers-hub-fnuww",
      logo: "uploads/company/logos/685212f735f8bfe83494c50f05d9068555ee6e2d.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Content Writing Intern",
      company_name: "Webenetic Private Limited",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "digital marketing",
      stipend_type: "Fixed",
      stipend: "7000 per day",
      days_left: 18,
      slug: "digital-marketing-internship-at-webenetic-private-limited-b30sv",
      logo: "uploads/company/logos/78728533163986c67b3a708a1937216dd8e267a2.jpg",
    },
    {
      internship_quality: "Normal",
      title: "3D Animation",
      company_name: "Ransfire",
      location: "bangalore,delhi,pune,gurgaon,mumbai,hyderabad",
      internship_type: "Work From Home",
      category_name: "video editor",
      stipend_type: "Variable",
      stipend: "7000 - 10000 per month",
      days_left: 18,
      slug: "video-editor-internship-at-ransfire-kesxg",
      logo: "uploads/company/logos/119e402fc4423e36b9e8330b46fa06701a573ff7.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Marketing Intern",
      company_name: "RFLABS",
      location: "chennai",
      internship_type: "Full Time",
      category_name: "marketing",
      stipend_type: "Fixed",
      stipend: "5000 per month",
      days_left: 16,
      slug: "marketing-internship-at-rflabs-1bdto",
      logo: "uploads/company/logos/97f070cf3195897ba484392cf4462e75a9e04c31.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Sales Officer",
      company_name: "Laugh Out Loud Ventures",
      location: "mumbai,bangalore,delhi,pune,hyderabad",
      internship_type: "Part Time,Work From Home",
      category_name: "marketing",
      stipend_type: "Variable",
      stipend: "3000 - 6000 per month",
      days_left: 15,
      slug: "marketing-internship-at-laugh-out-loud-ventures-tz1ss",
      logo: "uploads/company/companylogos/62362fbf882221470f099d8d0a119df93ce19831/7e34b7356b30b3696d14fcab94c6e8989a42fd69com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "BE/BTech Internship (Pursuing candidates)",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-scmxb",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Internship for MCA students ",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-onbgg",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "CYBER SECURITY INTERN",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-yawex",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Data Science Intern",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Work From Home",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-mtazb",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Software Development Internship",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-ncc4a",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Internship (BE/BTech/MTech)",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time",
      category_name: "software development",
      stipend_type: "None",
      stipend: 0,
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-z0eie",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "python Internship",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Work From Home,Part Time",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-i8cgr",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Java Internship ",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-o38jd",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Web Development Internship",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-l8ztr",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Machine Learning Internship",
      company_name: "TechCiti Technologies Pvt.Ltd.",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "1000 per month",
      days_left: 14,
      slug: "software-development-internship-at-techciti-technologies-pvtltd-mx4xv",
      logo: "uploads/company/companylogos/53488030f892d6461aed81af622e2e33f2be459c/ab86ddce842adb4c0cddceee1cf244993bf8d98fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "E-Commerce Catalogue Intern",
      company_name: "Kult Cosmetics Pvt Ltd",
      location: "mumbai",
      internship_type: "",
      category_name: "E-Commerce",
      stipend_type: "Fixed",
      stipend: "10000 per month",
      days_left: 14,
      slug: "e-commerce-internship-at-kult-cosmetics-pvt-ltd-mwkok",
      logo: "uploads/company/logos/0374af2a02c68e26cdc4a354e1bcf7fd2866d7df.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Data Entry Operator",
      company_name: "BWA",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "real estate",
      stipend_type: "Fixed",
      stipend: "6000 per month",
      days_left: 13,
      slug: "real-estate-internship-at-bwa-zzgoa",
      logo: "uploads/company/logos/8948038c37cfae1d280272b77527a7b3918297f9.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Graphic Designing for Social Media Marketing",
      company_name: "Cloud Clothing",
      location:
        "chennai,mumbai,kolkata,nashik,gurgaon,delhi,hyderabad,visakhapatnam,madurai,coimbatore",
      internship_type: "Work From Home",
      category_name: "graphic designing",
      stipend_type: "None",
      stipend: 0,
      days_left: 13,
      slug: "graphic-designing-internship-at-cloud-clothing-peeny",
      logo: "uploads/company/logos/7eb18458b78fecdbb421b213580d8680c8988904.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Lead Generation Intern",
      company_name: "Intugine Technologies",
      location: "bangalore",
      internship_type: "Full Time",
      category_name: "business development",
      stipend_type: "Variable",
      stipend: "12000 - 15000 per month",
      days_left: 13,
      slug: "business-development-internship-at-intugine-technologies-gq1iy",
      logo: "uploads/company/logos/cb64edacfbfee89dc68b57dc7da52bdf6a941c7f.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Devops",
      company_name: "Beagle Cyber Innovations Private Limited",
      location: "thiruvananthapuram",
      internship_type: "Full Time",
      category_name: "it and computers",
      stipend_type: "Fixed",
      stipend: "2000 per month",
      days_left: 13,
      slug: "it-and-computers-internship-at-beagle-cyber-innovations-private-limited-yst3a",
      logo: "uploads/company/logos/f82544c04aee7e79356f7305c176f84a26b4868c.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Digital Marketing Internship ",
      company_name: "Savage & Palmer",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "digital marketing",
      stipend_type: "Fixed",
      stipend: "2000 per month",
      days_left: 12,
      slug: "digital-marketing-internship-at-savage-palmer-xfex2",
      logo: "uploads/company/companylogos/34c2fed3559223e585b743e139a9f08d707bf2e1/a1c234859838d88dc45961f9322429f636874ce2com.png",
    },
    {
      internship_quality: "Normal",
      title: "Community Manager",
      company_name: "Awesome Sauce Creative Pvt. Ltd.",
      location: "lucknow",
      internship_type: "Full Time",
      category_name: "branding",
      stipend_type: "Fixed",
      stipend: "5000 per month",
      days_left: 12,
      slug: "branding-internship-at-awesome-sauce-creative-pvt-ltd-6o3hc",
      logo: "uploads/company/logos/f826d370a6213cc7fbccf70167447a0e39233f0f.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Content Writing Internship",
      company_name: "lifeisoutside.com",
      location: "bangalore",
      internship_type: "Full Time,Work From Home",
      category_name: "content writing",
      stipend_type: "Variable",
      stipend: "6000 - 15000 per month",
      days_left: 11,
      slug: "content-writing-internship-at-lifeisoutsidecom-esugr",
      logo: "uploads/company/logos/a63e097b54eaeb970556c604cc96e9a09ed8c1aa.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Marketing Intern",
      company_name: "Inkoop",
      location: "bangalore",
      internship_type: "Full Time,Work From Home",
      category_name: "marketing",
      stipend_type: "Fixed",
      stipend: "12000 per month",
      days_left: 9,
      slug: "marketing-internship-at-inkoop-g8djm",
      logo: "uploads/company/logos/9436af2d9a0a9b14c7d31b863b8837fa8b004cd4.jpg",
    },
    {
      internship_quality: "Normal",
      title: "SAP Executive",
      company_name: "CYBERCITY BUILDERS & DEVELOPERS PVT LTD",
      location: "hyderabad",
      internship_type: "Full Time",
      category_name: "Management Information System",
      stipend_type: "Fixed",
      stipend: "5000 per month",
      days_left: 9,
      slug: "management-information-system-internship-at-cybercity-builders-developers-pvt-ltd-nf416",
      logo: "uploads/company/companylogos/7fdc91144fbd29674a052bb166a688336c24c91a/e16df33e34a0ae69d83cca7ccd8ad47dd59a619acom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Business Development  Intern ",
      company_name: "Squareroute Tech Pvt. Ltd.",
      location: "pune",
      internship_type: "Full Time,Part Time,Work From Home",
      category_name: "Startup Incubation",
      stipend_type: "Incentive Based",
      stipend: "300 per sale",
      days_left: 9,
      slug: "startup-incubation-internship-at-squareroute-tech-pvt-ltd-iqj13",
      logo: "uploads/company/logos/164e70c486d83648addc5fc8d4cc9ed121acb585.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Content Management",
      company_name: "Tech2globe Web Solutions LLP",
      location: "delhi",
      internship_type: "Full Time",
      category_name: "others",
      stipend_type: "Fixed",
      stipend: "8000 per month",
      days_left: 9,
      slug: "others-internship-at-tech2globe-web-solutions-llp-nohli",
      logo: "uploads/company/companylogos/34e42d1279fc1bdc8e0954f11ca30ac73f9920d8/075d164e2911e50d6168b3dbaf9badf8cd676462com.png",
    },
    {
      internship_quality: "Normal",
      title: "CA Article ship ",
      company_name: "NeoGrowth Credit Pvt. Ltd.",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "ca articleship",
      stipend_type: "Fixed",
      stipend: "10000 per month",
      days_left: 8,
      slug: "ca-articleship-internship-at-neogrowth-credit-pvt-ltd-vvxz0",
      logo: "uploads/company/logos/a8d00b90034cfc94af16c8f353ee755564598bd4.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Graphic Design Intern",
      company_name: "DIBC",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "graphic designing",
      stipend_type: "Variable",
      stipend: "5000 - 15000 per month",
      days_left: 8,
      slug: "graphic-designing-internship-at-dibc-6ifsr",
      logo: "uploads/company/companylogos/b666213054c4a46dca64c77096f26c7be7d32630/089e4392566e10879a428bbfd819f37abb18408fcom.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Internship Program For Electrical Engineering Stud",
      company_name: "EVAVO WELLNESS & SOLUTIONS LLP",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "electronics engineering",
      stipend_type: "Fixed",
      stipend: "8000 per month",
      days_left: 7,
      slug: "electronics-engineering-internship-at-evavo-wellness-solutions-llp-8fere",
      logo: "uploads/company/companylogos/b1d37ce6289d72ee624d65f8422795a903a71a6f/68afb2eae34f20db5e41a3964d2b407fd7648131com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Business Development Intern",
      company_name: "EVAVO WELLNESS & SOLUTIONS LLP",
      location: "mumbai",
      internship_type: "",
      category_name: "business development",
      stipend_type: "Variable",
      stipend: "8000 - 14000 per month",
      days_left: 7,
      slug: "business-development-internship-at-evavo-wellness-solutions-llp-tymee",
      logo: "uploads/company/companylogos/b1d37ce6289d72ee624d65f8422795a903a71a6f/68afb2eae34f20db5e41a3964d2b407fd7648131com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Sales Coordinator",
      company_name: "EVAVO WELLNESS & SOLUTIONS LLP",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "sales",
      stipend_type: "Variable",
      stipend: "5000 - 10000 per month",
      days_left: 7,
      slug: "sales-internship-at-evavo-wellness-solutions-llp-4yyrr",
      logo: "uploads/company/companylogos/b1d37ce6289d72ee624d65f8422795a903a71a6f/68afb2eae34f20db5e41a3964d2b407fd7648131com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Human Resource Associate",
      company_name: "Laugh Out Loud Ventures",
      location:
        "mumbai,delhi,bangalore,hyderabad,chennai,kolkata,jaipur,pune,surat",
      internship_type: "Work From Home",
      category_name: "human resources",
      stipend_type: "Variable",
      stipend: "1000 - 5000 per month",
      days_left: 6,
      slug: "human-resources-internship-at-laugh-out-loud-ventures-yuqy5",
      logo: "uploads/company/companylogos/62362fbf882221470f099d8d0a119df93ce19831/7e34b7356b30b3696d14fcab94c6e8989a42fd69com.jpg",
    },
    {
      internship_quality: "Normal",
      title: "BD Intern",
      company_name: "Nviron Services OPC Pvt Ltd (miindmymiind.com)",
      location: "gurgaon",
      internship_type: "Part Time",
      category_name: "business development",
      stipend_type: "Incentive Based",
      stipend: "1000 per sale",
      days_left: 6,
      slug: "business-development-internship-at-nviron-services-opc-pvt-ltd-miindmymiindcom-d3efp",
      logo: "",
    },
    {
      internship_quality: "Normal",
      title: "Business Develoment",
      company_name: "Pet Set Go",
      location: "delhi",
      internship_type: "Full Time",
      category_name: "business development",
      stipend_type: "Fixed",
      stipend: "15000 per month",
      days_left: 5,
      slug: "business-development-internship-at-pet-set-go-i2hng",
      logo: "uploads/company/logos/fc6d7070762db285ed31c1e7501713f6de3cd737.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Social Media Intern",
      company_name: "Skrap",
      location: "mumbai,bangalore",
      internship_type: "Full Time,Work From Home",
      category_name: "social media",
      stipend_type: "Fixed",
      stipend: "6000 per month",
      days_left: 7,
      slug: "social-media-internship-at-skrap-vuzni",
      logo: "uploads/company/logos/86ef4508ab426a8a48afca122d04bb9bbbd9916e.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Software Developer Intern",
      company_name: "Pplwork",
      location: "gurgaon",
      internship_type: "Full Time",
      category_name: "engineering",
      stipend_type: "Fixed",
      stipend: "12000 per month",
      days_left: 7,
      slug: "engineering-internship-at-pplwork-9jmqu",
      logo: "uploads/company/logos/5f5819a638d350334857744a3faafaccac83b2da.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Opertaions Intern",
      company_name: "Kult Cosmetics Pvt Ltd",
      location: "mumbai",
      internship_type: "",
      category_name: "E-Commerce",
      stipend_type: "Fixed",
      stipend: "10000 per month",
      days_left: 5,
      slug: "e-commerce-internship-at-kult-cosmetics-pvt-ltd-qbd1g",
      logo: "uploads/company/logos/0374af2a02c68e26cdc4a354e1bcf7fd2866d7df.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Social Media Internship",
      company_name: "Red Cherry Entertainment",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "advertising",
      stipend_type: "Fixed",
      stipend: "6000 per month",
      days_left: 5,
      slug: "advertising-internship-at-red-cherry-entertainment-vx2y7",
      logo: "uploads/company/logos/34fa201f3b951ffcc83f1717a260a8b515757c07.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Sales and Marketing Executive",
      company_name: "Mpower2gether",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "sales",
      stipend_type: "Incentive Based",
      stipend: "5000 per sale",
      days_left: 5,
      slug: "sales-internship-at-mpower2gether-ge3vd",
      logo: "uploads/company/logos/82c6b2935e0523bcee710a495cb244bea3b6f3fc.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Content Writer",
      company_name: "Cloud Clothing",
      location:
        "chennai,bangalore,delhi,mumbai,kolkata,gurgaon,chandigarh,nashik,madurai,coimbatore",
      internship_type: "Work From Home",
      category_name: "content writing",
      stipend_type: "None",
      stipend: 0,
      days_left: 4,
      slug: "content-writing-internship-at-cloud-clothing-96huw",
      logo: "uploads/company/logos/7eb18458b78fecdbb421b213580d8680c8988904.jpg",
    },
    {
      internship_quality: "Normal",
      title: "HR Consultants, HR Assistant, HR Recruiter",
      company_name: "Mpower2gether",
      location: "bangalore",
      internship_type: "Part Time,Work From Home",
      category_name: "HR",
      stipend_type: "Incentive Based",
      stipend: "5000 per sale",
      days_left: 4,
      slug: "hr-internship-at-mpower2gether-bbc6a",
      logo: "uploads/company/logos/82c6b2935e0523bcee710a495cb244bea3b6f3fc.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Software Intern",
      company_name: "Teqie",
      location: "chennai",
      internship_type: "Full Time",
      category_name: "technology",
      stipend_type: "Fixed",
      stipend: "12000 per month",
      days_left: 3,
      slug: "technology-internship-at-teqie-6vhhv",
      logo: "uploads/company/logos/a7ddbc4147d010073b013f05a71fda592958c7f1.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Business Consultant",
      company_name: "Rosefield Energy Tech Pvt Ltd",
      location: "mumbai",
      internship_type: "Full Time",
      category_name: "consulting",
      stipend_type: "Expenses Covered",
      days_left: 3,
      slug: "consulting-internship-at-rosefield-energy-tech-pvt-ltd-emmxk",
      logo: "uploads/company/logos/a625e2646b3f3c1d7964d982c0c0b9f5a424e1c1.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Tech Support",
      company_name: "Metromax Group",
      location: "bangalore",
      internship_type: "Full Time",
      category_name: "software development",
      stipend_type: "Fixed",
      stipend: "10000 per month",
      days_left: 2,
      slug: "software-development-internship-at-metromax-group-dk13p",
      logo: "uploads/company/logos/a28ba6ba99e637dcecdd6487cab5501eab256264.jpg",
    },
    {
      internship_quality: "Normal",
      title: "Content Curator",
      company_name: "Gokrazee Innovations Private Limited",
      location:
        "mumbai,delhi,bangalore,kolkata,pune,chennai,hyderabad,jaipur,ahmedabad",
      internship_type: "Work From Home,Part Time",
      category_name: "Content Operations",
      stipend_type: "Fixed",
      stipend: "5000 per month",
      days_left: 2,
      slug: "content-operations-internship-at-gokrazee-innovations-private-limited-saheh",
      logo: "uploads/company/logos/6c0a3b959003ddb8e782d29244401adfea28a06d.jpg",
    },
    {
      internship_quality: "Normal",
      title: "contend writing (virtual Internship)",
      company_name: "Dealivore",
      location:
        "delhi,pune,bangalore,hyderabad,ahmedabad,chennai,kolkata,indore,nagpur,bhopal",
      internship_type: "Work From Home",
      category_name: "content writing",
      stipend_type: "None",
      stipend: 0,
      days_left: 2,
      slug: "content-writing-internship-at-dealivore-ug6q1",
      logo: "uploads/company/logos/2b8a2bf46894f1c017cfd765aabf80f70d55955a.jpg",
    },
    {
      internship_quality: "Normal",
      title: "HR internship for freshers|Freshers HR internship",
      company_name: "8 Views",
      location: "hyderabad",
      internship_type: "Full Time",
      category_name: "human resources",
      stipend_type: "Fixed",
      stipend: "5000 per month",
      days_left: 1,
      slug: "human-resources-internship-at-8-views-3708y",
      logo: "uploads/company/logos/e3e69604e7f14b6a6c1686876aea28eacd667763.jpg",
    },
    {
      internship_quality: "Normal",
      title: "social media",
      company_name: "Shari Academy of Professional Photography",
      location: "mumbai",
      internship_type: "Full Time,Work From Home",
      category_name: "social media",
      stipend_type: "Expenses Covered",
      days_left: 1,
      slug: "social-media-internship-at-shari-academy-of-professional-photography-sql04",
      logo: "uploads/company/companylogos/ebf1045c6e79f0b76cf47ead0d51b63bcfcd13d2/8adfd2a2b87fb64ac772be140b8ccf7308bb1ec1com.png",
    },
    {
      internship_quality: "Normal",
      title: "Video Editer",
      company_name: "Shari Academy of Professional Photography",
      location: "mumbai",
      internship_type: "Full Time,Work From Home",
      category_name: "photography and videography",
      stipend_type: "Expenses Covered",
      days_left: 1,
      slug: "photography-and-videography-internship-at-shari-academy-of-professional-photography-p791x",
      logo: "uploads/company/companylogos/ebf1045c6e79f0b76cf47ead0d51b63bcfcd13d2/8adfd2a2b87fb64ac772be140b8ccf7308bb1ec1com.png",
    },
    {
      internship_quality: "Normal",
      title: "Photoshop Intern",
      company_name: "Shari Academy of Professional Photography",
      location: "mumbai",
      internship_type: "Full Time,Work From Home",
      category_name: "photography and videography",
      stipend_type: "Expenses Covered",
      days_left: 1,
      slug: "photography-and-videography-internship-at-shari-academy-of-professional-photography-x4xnn",
      logo: "uploads/company/companylogos/ebf1045c6e79f0b76cf47ead0d51b63bcfcd13d2/8adfd2a2b87fb64ac772be140b8ccf7308bb1ec1com.png",
    },
    {
      internship_quality: "Normal",
      title: "Business Development Exceutive",
      company_name: "www.Franchiseapply.com",
      location: "lucknow,delhi,kanpur",
      internship_type: "Full Time,Work From Home",
      category_name: "business development",
      stipend_type: "Incentive Based",
      stipend: "4500 per sale",
      days_left: 1,
      slug: "business-development-internship-at-wwwfranchiseapplycom-0gvdn",
      logo: "uploads/company/logos/7465535cd06f447823c8d0b3aa0a0da07c91a8ce.jpg",
    },
  ],
  preferences: [
    {
      key: 2,
      value: 2,
      text: "advertising",
    },
    {
      key: 4,
      value: 4,
      text: "app design and development",
    },
    {
      key: 10,
      value: 10,
      text: "branding",
    },
    {
      key: 11,
      value: 11,
      text: "business development",
    },
    {
      key: 12,
      value: 12,
      text: "ca articleship",
    },
    {
      key: 42,
      value: 42,
      text: "consulting",
    },
    {
      key: 14,
      value: 14,
      text: "content writing",
    },
    {
      key: 15,
      value: 15,
      text: "digital marketing",
    },
    {
      key: 17,
      value: 17,
      text: "electronics engineering",
    },
    {
      key: 50,
      value: 50,
      text: "engineering",
    },
    {
      key: 20,
      value: 20,
      text: "general management",
    },
    {
      key: 21,
      value: 21,
      text: "graphic designing",
    },
    {
      key: 22,
      value: 22,
      text: "human resources",
    },
    {
      key: 52,
      value: 52,
      text: "it and computers",
    },
    {
      key: 29,
      value: 29,
      text: "marketing",
    },
    {
      key: 44,
      value: 44,
      text: "others",
    },
    {
      key: 32,
      value: 32,
      text: "photography and videography",
    },
    {
      key: 36,
      value: 36,
      text: "real estate",
    },
    {
      key: 48,
      value: 48,
      text: "sales",
    },
    {
      key: 38,
      value: 38,
      text: "social media",
    },
    {
      key: 40,
      value: 40,
      text: "software development",
    },
    {
      key: 41,
      value: 41,
      text: "web design and development",
    },
  ],
  cities: [
    {
      key: "lucknow",
      value: "lucknow",
      text: "lucknow",
    },
    {
      key: "delhi",
      value: "delhi",
      text: "delhi",
    },
    {
      key: "kanpur",
      value: "kanpur",
      text: "kanpur",
    },
    {
      key: "mumbai",
      value: "mumbai",
      text: "mumbai",
    },
    {
      key: "hyderabad",
      value: "hyderabad",
      text: "hyderabad",
    },
    {
      key: "pune",
      value: "pune",
      text: "pune",
    },
    {
      key: "bangalore",
      value: "bangalore",
      text: "bangalore",
    },
    {
      key: "ahmedabad",
      value: "ahmedabad",
      text: "ahmedabad",
    },
    {
      key: "chennai",
      value: "chennai",
      text: "chennai",
    },
    {
      key: "kolkata",
      value: "kolkata",
      text: "kolkata",
    },
    {
      key: "indore",
      value: "indore",
      text: "indore",
    },
    {
      key: "nagpur",
      value: "nagpur",
      text: "nagpur",
    },
    {
      key: "bhopal",
      value: "bhopal",
      text: "bhopal",
    },
    {
      key: "jaipur",
      value: "jaipur",
      text: "jaipur",
    },
    {
      key: "gurgaon",
      value: "gurgaon",
      text: "gurgaon",
    },
    {
      key: "chandigarh",
      value: "chandigarh",
      text: "chandigarh",
    },
    {
      key: "nashik",
      value: "nashik",
      text: "nashik",
    },
    {
      key: "madurai",
      value: "madurai",
      text: "madurai",
    },
    {
      key: "coimbatore",
      value: "coimbatore",
      text: "coimbatore",
    },
    {
      key: "surat",
      value: "surat",
      text: "surat",
    },
    {
      key: "thiruvananthapuram",
      value: "thiruvananthapuram",
      text: "thiruvananthapuram",
    },
    {
      key: "visakhapatnam",
      value: "visakhapatnam",
      text: "visakhapatnam",
    },
    {
      key: "sonipat",
      value: "sonipat",
      text: "sonipat",
    },
    {
      key: "meerut",
      value: "meerut",
      text: "meerut",
    },
    {
      key: "noida",
      value: "noida",
      text: "noida",
    },
    {
      key: "thane",
      value: "thane",
      text: "thane",
    },
    {
      key: "faridabad",
      value: "faridabad",
      text: "faridabad",
    },
  ],
  types: [
    {
      key: "Full Time",
      value: "Full Time",
      text: "Full Time",
    },
    {
      key: "Part Time",
      value: "Part Time",
      text: "Part Time",
    },
    {
      key: "Work From Home",
      value: "Work From Home",
      text: "Work From Home",
    },
  ],
  totalPages: 1,
};

localStorage.setItem("data", JSON.stringify(data));
